'use client';
import {useState, useEffect, useRef, type ReactNode} from 'react';
import {ArrowUpRight, Command, Send, ExternalLink, Minus, Maximize2, X} from 'lucide-react';
import EmailContact from '@/components/desktop/email-contact';
import Activity from '@/components/desktop/activity';
import MacOSDock from '@/components/desktop/mac-os-dock';
import {Menubar,MenubarMenu,MenubarTrigger,MenubarContent,MenubarItem} from '@/components/ui/menubar';

type AppId='work'|'activity'|'contact';
const apps=[
 {id:'work',name:'Selected work',icon:'/icons/fomo-app.svg'},
 {id:'activity',name:'GitHub activity',icon:'/icons/github-app.svg'},
 {id:'contact',name:'Get in touch',icon:'/icons/mail.png'},
];
const names:Record<AppId,string>={work:'Selected work',activity:'GitHub activity',contact:'Get in touch'};
function Out({href,children,className=''}:{href:string;children:ReactNode;className?:string}){return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16}/></a>}
type WindowProps={id:AppId;children:ReactNode;open:AppId[];front:AppId;expanded:AppId|null;setFront:(id:AppId)=>void;setOpen:React.Dispatch<React.SetStateAction<AppId[]>>;setExpanded:(id:AppId|null)=>void};
 function Window({id,children,open,front,expanded,setFront,setOpen,setExpanded}:WindowProps){
 const [position,setPosition]=useState({x:0,y:0});
 const positionRef=useRef(position);positionRef.current=position;
 const drag=useRef<{scale:number;pointer:number;startX:number;startY:number;x:number;y:number;minX:number;maxX:number;minY:number;maxY:number}|null>(null);
 const frame=useRef<HTMLElement>(null);
 useEffect(()=>{const reset=()=>setPosition({x:0,y:0});window.addEventListener('resize',reset);return()=>window.removeEventListener('resize',reset)},[]);
 function startDrag(event:React.PointerEvent<HTMLElement>){
  if(event.button!==0||expanded===id||!window.matchMedia('(min-width:800px)').matches||(event.target as HTMLElement).closest('button,a'))return;
  const rect=frame.current!.getBoundingClientRect(),p=positionRef.current,scale=rect.width/frame.current!.offsetWidth;
  drag.current={scale,pointer:event.pointerId,startX:event.clientX,startY:event.clientY,x:p.x,y:p.y,minX:p.x+(12-rect.left)/scale,maxX:p.x+(window.innerWidth-12-rect.right)/scale,minY:p.y+(42-rect.top)/scale,maxY:p.y+(window.innerHeight-92-rect.bottom)/scale};
  event.currentTarget.setPointerCapture(event.pointerId);setFront(id);event.preventDefault();
 }
 function moveDrag(event:React.PointerEvent<HTMLElement>){const d=drag.current;if(!d||d.pointer!==event.pointerId)return;setPosition({x:Math.max(d.minX,Math.min(d.maxX,d.x+(event.clientX-d.startX)/d.scale)),y:Math.max(d.minY,Math.min(Math.max(d.minY,d.maxY),d.y+(event.clientY-d.startY)/d.scale))})}
 function endDrag(){drag.current=null}
 function moveWithKeys(event:React.KeyboardEvent<HTMLElement>){if(event.target!==event.currentTarget||expanded===id||!window.matchMedia('(min-width:800px)').matches||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const rect=frame.current!.getBoundingClientRect(),p=positionRef.current,scale=rect.width/frame.current!.offsetWidth,step=event.shiftKey?30:10;setFront(id);setPosition({x:Math.max(p.x+(12-rect.left)/scale,Math.min(p.x+(window.innerWidth-12-rect.right)/scale,p.x+(event.key==='ArrowRight'?step:event.key==='ArrowLeft'?-step:0))),y:Math.max(p.y+(42-rect.top)/scale,Math.min(Math.max(p.y+(42-rect.top)/scale,p.y+(window.innerHeight-92-rect.bottom)/scale),p.y+(event.key==='ArrowDown'?step:event.key==='ArrowUp'?-step:0)))})}
 function hide(){const remaining=open.filter(a=>a!==id);setOpen(remaining);if(front===id&&remaining.length)setFront(remaining[remaining.length-1]);setExpanded(null)}return open.includes(id)?<section ref={frame} id={id} aria-label={names[id]} className={`window window-${id} ${front===id?'focused':''} ${expanded===id?'expanded':''}`} onPointerDown={()=>setFront(id)} style={{zIndex:front===id?5:2,transform:expanded===id?undefined:`translate(${position.x}px, ${position.y}px)`}}><header className="titlebar" tabIndex={0} aria-label={`${names[id]} title bar. Drag or use arrow keys to move the window.`} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} onLostPointerCapture={endDrag} onKeyDown={moveWithKeys}><div className="traffic"><button aria-label={`Close ${names[id]}`} className="close" onClick={hide}><X/></button><button aria-label={`Minimize ${names[id]}`} className="minimize" onClick={hide}><Minus/></button><button aria-label={`${expanded===id?'Restore':'Expand'} ${names[id]}`} className="maximize" onClick={()=>setExpanded(expanded===id?null:id)}><Maximize2/></button></div><div className="window-title"><strong><img className={id==='work'?'brand-icon fomo-eyes':id==='activity'?'brand-icon github-mark':'brand-icon'} src={id==='work'?'/icons/fomo-eyes.svg':id==='activity'?'/icons/github.svg':'/icons/mail.png'} alt=""/>{id==='contact'?'Mail':names[id]}</strong><span>{id==='work'?'Fomo · GTM Internship':id==='activity'?'ouchip':'/ new message'}</span></div><div className="window-actions">{id==='contact'?<a href="mailto:luchi@lucianopinilla.com?subject=Let%E2%80%99s%20talk" aria-label="Write an email to Luciano" title="Write an email"><Send size={17}/></a>:<><button aria-label={`${expanded===id?'Restore':'Expand'} ${names[id]} window`} title="Expand window" onClick={()=>setExpanded(expanded===id?null:id)}><Maximize2 size={16}/></button><a href={id==='work'?'/campus/':id==='activity'?'https://github.com/ouchip':'https://x.com/foezart'} target="_blank" rel="noopener noreferrer" aria-label={`Open ${names[id]} in a new tab`} title="Open in new tab"><ExternalLink size={16}/></a></>}</div></header>{children}</section>:null}
export default function Home(){
 const [open,setOpen]=useState<AppId[]>(['work','activity','contact']);
 const [front,setFront]=useState<AppId>('work');
 const [expanded,setExpanded]=useState<AppId|null>(null);
 function show(id:AppId){setOpen(v=>v.includes(id)?v:[...v,id]);setFront(id);}


 return <main className="desktop"><div className="wallpaper"/><header className="topbar"><button className="monogram" aria-label="Restore desktop" onClick={()=>{setOpen(['work','activity','contact']);setFront('work');setExpanded(null)}}><Command size={17}/></button><Menubar className="desktop-menu"><MenubarMenu><MenubarTrigger className="app-name">Luciano Pinilla</MenubarTrigger><MenubarContent><MenubarItem onClick={()=>show('contact')}>Get in touch</MenubarItem></MenubarContent></MenubarMenu><MenubarMenu><MenubarTrigger>Work</MenubarTrigger><MenubarContent><MenubarItem onClick={()=>show('work')}>Fomo Campus</MenubarItem><MenubarItem onClick={()=>show('activity')}>GitHub activity</MenubarItem></MenubarContent></MenubarMenu><MenubarMenu><MenubarTrigger>Window</MenubarTrigger><MenubarContent>{apps.map(a=><MenubarItem key={a.id} onClick={()=>show(a.id as AppId)}>{a.name}</MenubarItem>)}<MenubarItem onClick={()=>{setOpen([]);setExpanded(null)}}>Show desktop</MenubarItem></MenubarContent></MenubarMenu></Menubar><div className="menu-status"><LocalClock/></div></header>
 <div className="desktop-heading"><h1>luciano<br/><span className="name-space"> </span>pinilla</h1><div className="identity-links"><a href="https://x.com/foezart" target="_blank" rel="noopener noreferrer">@foezart ↗</a></div></div>
 <div className="workspace">
 <Window open={open} front={front} expanded={expanded} setFront={setFront} setOpen={setOpen} setExpanded={setExpanded} id="work"><div className="work-toolbar"><span><img className="fomo-eyes toolbar-brand" src="/icons/fomo-eyes.svg" alt="Fomo"/> My Work / Fomo Campus</span><span>01</span></div><a href="/campus/" target="_blank" rel="noopener noreferrer" className="project-image"><img src="/images/fomo-village.jpg" alt="The Greek village from the Fomo Campus website"/><span className="project-image-label">fomo<span>campus</span></span><span className="image-arrow"><ArrowUpRight size={24}/></span></a><div className="project-copy"><div className="eyebrow">FOMO CAMPUS</div><h2>GTM Internship at Fomo.</h2><p>Handling campus outreach, onboarding fraternities into Greek Wars, and building brand awareness for Fomo.</p><div className="project-bottom"><span className="project-tags">Web design <b>·</b> Development</span><Out href="/campus/">See page</Out></div></div></Window>
 <Window open={open} front={front} expanded={expanded} setFront={setFront} setOpen={setOpen} setExpanded={setExpanded} id="activity"><div className="activity-body"><div className="activity-heading"><div><h2>A little more green.</h2></div><img className="github-mark activity-brand" src="/icons/github.svg" alt="GitHub"/></div><Activity/><Out className="activity-link" href="https://github.com/ouchip">github.com/ouchip</Out></div></Window>
 <Window open={open} front={front} expanded={expanded} setFront={setFront} setOpen={setOpen} setExpanded={setExpanded} id="contact"><div className="contact-body mail-note"><div className="contact-address-line"><span className="mail-field-label">To:</span><EmailContact email="luchi@lucianopinilla.com"/></div><div className="contact-subject-line"><span className="mail-field-label">Subject:</span><span>A project, an opportunity, or a hello</span></div><div className="contact-message"><p>Send a note, or reach out on <a className="inline-x-link" href="https://x.com/foezart" target="_blank" rel="noopener noreferrer" aria-label="Reach out to @foezart on X"><img className="social-mark inline-x" src="/icons/x.svg" alt="X"/></a>.</p><div className="contact-signature"><span>luciano pinilla</span><span aria-hidden="true">·</span><a href="https://www.linkedin.com/in/luciano-pinilla-134668381/" target="_blank" rel="noopener noreferrer" className="signature-linkedin"><img src="/icons/linkedin.svg" alt=""/>LinkedIn</a><span aria-hidden="true">·</span><a className="signature-x" href="https://x.com/foezart" target="_blank" rel="noopener noreferrer"><img className="social-mark" src="/icons/x.svg" alt="X"/> @foezart</a></div></div></div></Window>
 </div><footer className="dock-wrap" aria-label="Desktop apps"><MacOSDock apps={apps} openApps={open} onAppClick={id=>show(id as AppId)}/></footer></main>
}


function LocalClock(){const [time,setTime]=useState('');
 useEffect(()=>{const tick=()=>setTime(new Date().toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'}));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);
return <time className="desktop-clock" suppressHydrationWarning>{time}</time>}
